apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hand-cricket
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  ingressClassName: nginx
  rules:
    - host: hand-cricket.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hand-cricket
                port:
                  number: 80
